In [2]:
import torch
import torch.tensor as tensor

In [18]:
t = tensor([
    [0.,1,0],
    [2,0,2],
    [0,3,0]
])

In [19]:
t.shape

torch.Size([3, 3])

In [20]:
t.sum()

tensor(8.)

In [21]:
t.sum(axis=1)

tensor([1., 4., 3.])

In [22]:
#No of elements
t.numel()

9

In [23]:
t.prod(), t.sum(), t.mean(), t.std()

(tensor(0.), tensor(8.), tensor(0.8889), tensor(1.1667))

In [24]:
t.dtype

torch.float32

## Argmax

In [29]:
t = torch.tensor([
    [1.,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
])

In [30]:
t.max()

tensor(5.)

In [31]:
t.argmax()

tensor(11)

In [32]:
t.flatten()[11]

tensor(5.)

In [34]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [35]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [37]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [38]:
t.argmax(dim=1)

tensor([3, 2, 3])

## Conversions

In [41]:
t.argmax(dim=1).tolist()

[3, 2, 3]

In [42]:
t.argmax(dim=1).numpy()

array([3, 2, 3])